### PR TITLE
Add HTML_SMARTYPANTS_DASHES for toggling smart dashes

### PR DESCRIPTION
**Pull request by anthonyfok**
There may be cases where an end user (like me) would like to use SmartyPants except the smart dashes, hence this pull request adds a new `HTML_SMARTYPANTS_DASHES` flag to allow the user to turn off just the smart dashes.  :-)

What do you think?  :-)

### CODE REVIEW

**Comment by rtfb** [comment]
Missed this one. Looks good to me. Will merge if no objections are raised in couple days.

**Comment by spf13** [comment]
Please merge :)

**Comment by rtfb** [comment]
Well, I actually stumbled upon an (potential) objection myself... Since @anthonyfok submitted this one and he also was interested in #136, I was wondering whether this setting was meant to workaround the problem with #136. Or is this completely unrelated and only coincidentally involves two consecutive dashes? :-)

**Comment by rtfb** [comment]
OK, I've read the motivation over at corresponding PR to Hugo and see no downsides. In it goes.

**Comment by anthonyfok** [comment]
Wow, what a pleasant surprise!  Thank you so much @rtfb!
And thank you @spf13 for advocating for me!  :-)

(Sorry, I had been away, and hence the late reply to this thread.)

Cheers,
Anthony

**Pull request merged**
