### PR TITLE
Fix regession: index out of range panic in reference link (#172, #173)

### PR DESCRIPTION
**Pull request by tomkwok**
The previous fix got reverted/removed by new commits.

### CODE REVIEW

**Comment by rtfb** [comment]
What's up with the broken test?

**Comment by tomkwok** [comment]
Fixed

**Comment by rtfb** [comment]
Thanks! Could you also please add a test that reproduces the issue? That would greatly diminish the chances such a regression would reoccur.

**Comment by tomkwok** [comment]
Done. This is the naughty string: `[]:<`

**Comment by shurcooL** [comment]
I can confirm the test case causes a panic without the fix:

```
panic: runtime error: index out of range [recovered]
	panic: runtime error: index out of range

goroutine 52 [running]:
panic(0x17afe0, 0xc82000c070)
	/usr/local/go/src/runtime/panic.go:464 +0x3e6
testing.tRunner.func1(0xc8201a4090)
	/usr/local/go/src/testing/testing.go:467 +0x192
panic(0x17afe0, 0xc82000c070)
	/usr/local/go/src/runtime/panic.go:426 +0x4e9
github.com/russross/blackfriday.scanLinkRef(0xc820106400, 0xc820272f20, 0x4, 0x8, 0x3, 0x4, 0x4, 0x0, 0x0, 0x0)
```

And the fix causes it, while all tests pass.

LGTM. Shall we merge this @rtfb?

**Comment by shurcooL** [comment]
Friendly ping @rtfb.

**Comment by rtfb** [comment]
Yes! Sorry for the delay. I wanted to drill down the history to see when the regression happened, but couldn't find time for it until last night... Turns out I broke it with bcd6dd8 :-/. Now when I have it figured out, I can merge it and investigate later.

Thanks @tomkwok and @shurcooL!

**Pull request merged**
