### PR TITLE
Document SanitizedAnchorName algorithm, copy implementation.

### PR DESCRIPTION
**Pull request by dmitshur**
The goal of this change is to reduce number of non-standard library packages (repositories) that blackfriday imports (not counting imports used only for tests) from 1 to 0, and in turn, reduce the cost of importing blackfriday into other projects.

Do so by documenting the algorithm of `SanitizedAnchorName`, and include a copy of the small function inside blackfriday itself. The same functionality continues to be available in the original location, `github.com/shurcooL/sanitized_anchor_name.Create`. It can be used by existing users and those that look for a small package, and don't need all of blackfriday functionality. Existing users of blackfriday can use the new `SanitizedAnchorName` function directly and avoid an extra package import.

This change is a port of PR #352 from v1 into v2.

Updates #348.
Updates #350.

### CODE REVIEW

**Comment by dmitshur** [comment]
Friendly ping @rtfb, do you have a chance to review this?

/cc @julieqiu I think this PR may fix the issue that you ran into.

**Comment by rtfb** [comment]
Yep, looks good. Thanks, and sorry for the delay.

**Comment by dmitshur** [comment]
No problem! Thanks, I'll merge it now.

**Comment by rtfb** [comment]
Yeah, makes sense. I also want to check how https://github.com/russross/blackfriday/pull/515 works with broken reference tests, and if it pulls it off, we could merge that one as well. I'll try to do that in the coming days.

**Pull request merged**
