### PR TITLE
Change the public interface to use functional options

### PR DESCRIPTION
**Pull request by rtfb**
Convert the most important Blackfriday's function, `Markdown()`, to accept functional options (as per this Dave Cheney's post: https://dave.cheney.net/2014/10/17/functional-options-for-friendly-apis)

This dawned on me a bit late in the cycle, but thankfully just in time before we announce v2 with full lungs.

In essence, here's the main benefit: instead of calling `blackfriday.MarkdownCommon(input)`, you can now call `blackfriday.Markdown(input)`.

Instead of `blackfriday.MarkdownBasic(input)`, call `blackfriday.Markdown(input, WithNoExtensions())`.

And for a fully customized version:

``` go
blackfriday.Markdown(input, blackfriday.WithRefOverride(override), blackfriday.WithExtensions(exts), blackfriday.WithRenderer(yourRenderer))
```

I am also very tempted to take this chance to change the `input []byte` to `io.Reader`. Unfortunately, under the hood that would take a lot of changes and I can't do them quickly. What do you think, would it make sense to make the interface change now, while we're breaking compatibility anyway, but leave the implementation buffered as it is now?

### CODE REVIEW

**Comment by shurcooL** [comment]
I would probably rewrite that customized version to not scroll off-screen:

```Go
blackfriday.Markdown(input,
	blackfriday.WithRefOverride(override),
	blackfriday.WithExtensions(exts), blackfriday.WithRenderer(yourRenderer))
```

Just to give me a better idea of what it'd look like.

I have to admit this style hasn't fully grown on me yet, but I don't mind it. SGTM.

One thing, see an excellent writeup by @rakyll at https://rakyll.org/style-packages/, the "Provide examples to fill the gaps" section (btw @rakyll, I wish I could link to individual sections).

I think we should definitely provide examples in godoc that display all the common use cases with the new functional options approach. Both for helping people understand what's possible, and for convenience of copy pasting a good starting point.

From what I can tell, you've already done so in the documentation for `Markdown` func, which is 💯! I think it'd be a good idea to do it in the package comment as well. That way it'll show up on top of godoc where the package is introduced and described.

---

I am also very tempted to take this chance to change the input `[]byte` to `io.Reader`.

Providing an `io.Reader` is always easier than `[]byte`, right? If you have `[]byte`, you can wrap with `bytes.NewReader`, which is inexpensive (although copying out of that reader into `[]byte` is a little wasteful). If you have `io.Reader`, you pass it directly in. Providing `[]byte` when you have `io.Reader` requires reading it all first, which would be wasteful if the library doesn't need all bytes at once to make progress.

Can you remind me if we have plans to eventually do some streaming and on-the-fly processing, rather than simply dumping the entire `io.Reader` content into `[]byte` at the very beginning?

If so, then making that change of API to take `io.Reader` now, dump it to `[]byte` as first internally _for now_, and potentially doing more streaming later also SGTM.

Would it be a good or bad idea to provide two funcs in the API, one that takes `[]byte` and the other `io.Reader`?

**Comment by rakyll** [comment]
(@shurcooL, there are anchor links in the source but the titles are not made clickable by the theme. I am going to fix it today. See https://rakyll.org/style-packages/#provide-examples-to-fill-the-gaps. Thanks!)

**Comment by shurcooL** [comment]
About functional options, have you also considered just an `Options` struct? I.e.:

```Go
func Markdown(input []byte, opt *Options) { ... }

type Options struct {
	RefOverride ...
	Extensions ...
	Renderer ...
}
```

I guess that's similar to what we have with `MarkdownOptions` right now:

https://godoc.org/github.com/russross/blackfriday#MarkdownOptions

Except we could move `Renderer` parameter into options too (and possibly give it a sane default, making it optional).

**Comment by rtfb** [comment]
> About functional options, have you also considered just an `Options` struct?

Yes. Dave's article has a detailed rationale against that, but in short: option-less call becomes cumbersome. One would have to provide a `nil` or an `Options{}` while with functional options there's literally nothing.

---

WRT the `io.Reader`, I realized there's no point. The real win of having a streaming interface is when we can connect an `io.Reader` on one end with an `io.Writer` on the other without any buffering in between. But in our case this won't happen, because we produce an AST in the middle. And while a typical AST is quite shallow, list-like, things like TOC and refrence-style links make it necessary to buffer an entire document.

So, no streaming for Blackfriday :-/

**Comment by shurcooL** [comment]
> Yes.

Fair enough.

> Dave's article has a detailed rationale against that, but in short: option-less call becomes cumbersome. One would have to provide a nil or an Options{} while with functional options there's literally nothing.

Is that really the main reason? To me, seeing this in godoc:

```Go
func Process(..., opt *Options) ([]byte, error)
```

Is very very clear and readable, because it's so explicit. I can immediately look at the `Options` struct and instantly understand all of the options available:

```Go
type Options struct {
    Fragment  bool // Accept fragment of a source file (no package statement)
    AllErrors bool // Report all errors (not just the first 10 on different lines)

    Comments  bool // Print comments (true if nil *Options provided)
    TabIndent bool // Use tabs for indent (true if nil *Options provided)
    TabWidth  int  // Tab width (8 if nil *Options provided)

    FormatOnly bool // Disable the insertion and deletion of imports
}
```

In the end, for me, I find an `Options` struct much easier to write, and very easy to read. Functional options are somewhat easy to read (I have to guess that magic behind the scenes does the right thing, but I can't be as certain of it without spending more time looking at its internals), and more hard to write (which is why I think documenting some examples is so important).

However, that's just my POV. I've used options structs a lot, and functional options almost never. They might grow on me after more exposure, I don't know.

I'm not against trying them here, I just wanted to better understand the tradeoffs.

---

> The real win of having a streaming interface is when we can connect an io.Reader on one end with an io.Writer on the other without any buffering in between.

Precisely.

> But in our case this won't happen, because we produce an AST in the middle. And while a typical AST is quite shallow, list-like, things like TOC and refrence-style links make it necessary to buffer an entire document.

Makes sense. I suspected that could be the case. The ability to stream comes with hard requirement that limit what you're able to do in terms of processing, and Markdown (with extensions) is too powerful of a language to be able to get away without needing buffering.

**Comment by Ambrevar** [comment]
I like functional options.

What about #277 then?

Streaming: what about streaming possibilities if options like refs/TOC are off?

**Comment by rtfb** [comment]
> Streaming: what about streaming possibilities if options like refs/TOC are off?

Reference style links are standard, and we can't know whether an input document contains them until we parse it all, so, however disappointing that might sound, streaming is not an option for markdown processing... :-(

**Comment by Ambrevar** [comment]
Right, forgot about that.

v2 inbound, then.

**Comment by shurcooL** [comment]
Perhaps relevant, this discourse happened recently. https://twitter.com/rogpeppe/status/890483872605057024.

Specifically, the tweet refers to package [`cmp`](https://godoc.org/github.com/google/go-cmp/cmp).

**Comment by rtfb** [comment]
A very neat use of functional options indeed! And seems to be a useful package in general, thanks.

**Pull request merged**
