### PR TITLE
v2: Automatically set title from the titleblock if it is unspecified

### PR DESCRIPTION
**Pull request by Ambrevar**
Not bulletproof, but probably better than nothing.

### CODE REVIEW

**Comment by rtfb** [comment]
But... why? It's not obvious to me that such an obscure interaction between two unrelated extensions is better than nothing.

**Comment by Ambrevar** [comment]
The title is not an extension, it is a parameter of the HTML renderer. Basically, this would lead to more automation from the generator: start a page with

```
% My title
```

And the `<title>My title</title> will be set without any additional code needed on the user side.

**Comment by rtfb** [comment]
But the `HTMLRendererParameters.Title` is a part of an output only when using `CompletePage` extension. And then you consider a title only when a `Titleblock` extension is on. That couples these extensions in a very non-straightforward way.

**Comment by Ambrevar** [comment]
Right, forgot that I had completepage on. OK, forget this PR.

**Pull request closed without merging**
