### PR TITLE
Fix block parsing for fenced code blocks in lists

### PR DESCRIPTION
**Pull request by tfogo**
This is the fix for https://github.com/russross/blackfriday/issues/239 from @client9 and myself.

Sent a message in https://github.com/russross/blackfriday/issues/239 outlining the issues client9 faced with the tests and the fixes I made.

### CODE REVIEW

**Comment by tfogo** [comment]
cc @rtfb

**Comment by mistyhacks** [comment]
+1 hope this gets in ASAP! Thanks @tfogo!

**Comment by zacharysarah** [comment]
Thanks @tfogo! All the best for a quick approval! 🌟

**Comment by rtfb** [comment]
LGTM, thanks a lot!

**Pull request merged**
