### PR TITLE
Add definition lists extension support

### PR DESCRIPTION
**Pull request by vbatoufflet**
Hi,

This PR implements definition lists support as described [here](https://michelf.ca/projects/php-markdown/extra/#def-list).

This support is available as an extension using `EXTENSION_DEFINITION_LISTS`.

Hoping it will suits you.

King regards,

Vincent

### CODE REVIEW

**Comment by rtfb** [comment]
Looks good. This implements #144, right?

**Comment by vbatoufflet** [comment]
Indeed, it does.

However I discovered that there is a little bug in my implementation. I will fix it and let you know as soon as it will be ok.

**Comment by vbatoufflet** [comment]
Hi @rtfb,

I fixed the bug I found in the code I wrote. All should be fine now.

**Comment by rtfb** [comment]
Thank you!

**Pull request merged**
